export type TableListItem = { 
    emplid: any;
    sfcs: any; 
    mes: any;
    wms: any;
    lms: any;
    sap: any;
    eform: any;
    ciems: any;
    iccs: any;
    bys: any;
    newsku: any;
    eip: any;
    dcc: any;
    warRoom: any;
    tms: any;
    myfa: any;
    sqms: any;
    qcAudit: any;
    qams: any;
    ers: any;
    cal: any;
    impc: any;
    tiptop: any;
    ehs: any;
    epetition: any;
    icio: any;
    dlTraining: any;
    ems: any;
    fms: any;
    i4Systems: any;
    network:any;
    telephone: any;
    videoConference: any;
    infoSafety: any;
    cctv: any;
    swipeCard: any;
    antivirus:any;
    oaexchange:any;
    oaadManagement: any;
    oaSoftwareManagement: any;
    seServer: any;
    nifi: any;
    kafka: any;
    mqtt: any;
    logstash: any;
    rabbitMq: any;
    sds: any;
    powerBi: any;
    wkc: any;
    airflow: any;
    elasticsearch: any;
    hadoop: any;
    kudu: any;
    redis: any;
    mariaDb: any;
    mysql: any;
    sqlserver: any;
    oracle: any;
    postgresql: any;
    net: any;
    python: any;
    java: any;
    javascripts: any;
    angular: any;
    loopback: any;
    react: any;
    nodejs: any;
    flink: any;
    vba: any;
    r: any;
    typescripts: any;
    vue: any;
    ios:any;
    android:any;
    wechatApp: any;
    docker:any;
    k8s:any;
    gitlab:any;
    rancher:any;
    harbor:any;
    kibana:any;
    grafana:any;
    nocas: any;
    uipath: any;
    aaOcr: any;
    scrumMaster: any;
    techLead: any;
    translator: any;
    dataEngineer: any;
    fullStackDeveloper: any;
    developerFrontend: any;
    developerBackend: any;
    viriya: any;
    master: any;
    expert: any;
    

  };


  export type skillList = {  
    sfcs: any; 
    mes: any;
    wms: any;
    lms: any;
    sap: any;
    eform: any;
    ciems: any;
    iccs: any;
    bys: any;
    newsku: any;
    eip: any;
    dcc: any;
    warRoom: any;
    tms: any;
    myfa: any;
    sqms: any;
    qcAudit: any;
    qams: any;
    ers: any;
    cal: any;
    impc: any;
    tiptop: any;
    ehs: any;
    epetition: any;
    icio: any;
    dlTraining: any;
    ems: any;
    fms: any;
    i4Systems: any;
    network:any;
    telephone: any;
    videoConference: any;
    infoSafety: any;
    cctv: any;
    swipeCard: any;
    antivirus:any;
    oaexchange:any;
    oaadManagement: any;
    oaSoftwareManagement: any;
    seServer: any;
    nifi: any;
    kafka: any;
    mqtt: any;
    logstash: any;
    rabbitMq: any;
    sds: any;
    powerBi: any;
    wkc: any;
    airflow: any;
    elasticsearch: any;
    hadoop: any;
    kudu: any;
    redis: any;
    mariaDb: any;
    mysql: any;
    sqlserver: any;
    oracle: any;
    postgresql: any;
    net: any;
    cplus: any;
    cplusPlus: any;
    python: any;
    java: any;
    javascripts: any;
    angular: any;
    loopback: any;
    react: any;
    nodejs: any;
    flink: any;
    vba: any;
    r: any;
    typescripts: any;
    vue: any;
    ios:any;
    android:any;
    wechatApp: any;
    docker:any;
    k8s:any;
    gitlab:any;
    rancher:any;
    harbor:any;
    kibana:any;
    grafana:any;
    nocas: any;
    uipath: any;
    aaOcr: any;
    scrumMaster: any;
    techLead: any;
    translator: any;
    dataEngineer: any;
    fullStackDeveloper: any;
    developerFrontend: any;
    developerBackend: any;
    viriya: any;
    master: any;
    expert: any

  };

  export type site = {
    site?: string,  
  };
  export type  Dept = {
    dept?: string,  
  }; 